import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
          Start by simulating your own aquarium&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <Link
            href="/poissons"
            className={styles.card}
          >
            <h2>
              Poissons <span>-&gt;</span>
            </h2>
            <p>
              La liste des poissons d'aquarium.
            </p>
          </Link>

          <Link
            href="/Simulation"
            className={styles.card}
          >
            <h2>
              Simulation <span>-&gt;</span>
            </h2>
            <p>
            Simulez l'environnement de votre propre aquarium.
            </p>
          </Link>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>
              Tutoriel <span>-&gt;</span>
            </h2>
            <p>
            Apprenez comment démarrer un nouvel aquarium.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              A propos de nous <span>-&gt;</span>
            </h2>
            <p>
              Présentation de l'équipe derrière ce projet.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
