"""
Audit des données des poissons : liste les valeurs douteuses à vérifier à la main

Usage : python audit_data.py > ../docs/data-audit.md   (ou `make audit`)
"""

from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import Session

# Seuils au-delà desquels une valeur mérite une vérification
TEMP_MIN_TROPICAL = 16
TEMP_MAX_TROPICAL = 31
GH_MAX_PLAUSIBLE = 30
GH_MIN_HARD = 20
PH_MIN_PLAUSIBLE = 4.5
TAILLE_PISCIVORE = 30


@dataclass
class Issue:
    fish: str
    check: str
    detail: str


def audit(fishes: list[dict]) -> list[Issue]:
    """ Vérifie la cohérence de chaque poisson (dictionnaires au format de Poisson.as_dict)
    """
    issues = []

    def add(p, check, detail):
        issues.append(Issue(f"{p['nom_commun']} ({p['nom_scientifique']})", check, detail))

    for p in fishes:
        for k, label in (('ph', 'pH'), ('gh', 'GH'), ('temp', 'Température')):
            if p[f'{k}_mini'] > p[f'{k}_maxi']:
                add(p, 'Plage inversée', f"{label} {p[f'{k}_mini']} > {p[f'{k}_maxi']}")

        if p['temp_mini'] < TEMP_MIN_TROPICAL or p['temp_maxi'] > TEMP_MAX_TROPICAL:
            add(p, 'Température inhabituelle',
                f"{p['temp_mini']}–{p['temp_maxi']} °C (plage tropicale habituelle : "
                f"{TEMP_MIN_TROPICAL}–{TEMP_MAX_TROPICAL} °C)")

        if p['gh_maxi'] > GH_MAX_PLAUSIBLE or p['gh_mini'] >= GH_MIN_HARD:
            add(p, 'GH très élevé', f"GH {p['gh_mini']}–{p['gh_maxi']} : unité à vérifier (°d ou °f ?)")

        if p['ph_mini'] < PH_MIN_PLAUSIBLE:
            add(p, 'pH très acide', f"pH mini {p['ph_mini']}")

        if p['points'] is not None and p['nb_individus'] * p['points'] > p['litrage_mini']:
            add(p, 'Groupe minimum trop grand pour le volume minimum',
                f"{p['nb_individus']} × {p['points']} points = {p['nb_individus'] * p['points']} "
                f"> {p['litrage_mini']} L")

        if p['nom_mode_vie'] == 'solitaire' and p['nb_individus'] > 1:
            add(p, 'Solitaire en groupe', f"mode de vie « solitaire » mais {p['nb_individus']} individus minimum")

        if (p['taille'] >= TAILLE_PISCIVORE and p['regime'].startswith('carnivore')
                and p['nom_comportement'] in ('pacifique', 'peu agressif')):
            add(p, 'Grand carnivore classé paisible',
                f"{p['taille']} cm, {p['regime']}, comportement « {p['nom_comportement']} »")

    return issues


def to_markdown(issues: list[Issue], total: int) -> str:
    lines = [
        '# Data audit',
        '',
        f'Generated by `backend/audit_data.py` on the imported database ({total} fish). '
        'Each line is a value to check against a reliable source; confirmed fixes go to '
        '`backend/corrections.py`.',
        '',
        f'**{len(issues)} values to check.**',
    ]
    for check in dict.fromkeys(i.check for i in issues):
        lines += ['', f'## {check}', '', '| Fish | Detail |', '|---|---|']
        lines += [f'| {i.fish} | {i.detail} |' for i in issues if i.check == check]
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    from config import DSN
    from models import Poisson
    from models.meta import get_engine

    with Session(get_engine(DSN)) as db:
        fishes = [p.as_dict() for p in db.scalars(select(Poisson).order_by(Poisson.id))]
    print(to_markdown(audit(fishes), len(fishes)), end='')
