"""nom commun pas unique

Revision ID: c87c809c03a5
Revises: 48fc02eb4b59
Create Date: 2023-06-23 16:08:37.924791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87c809c03a5'
down_revision = '48fc02eb4b59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_poisson_nom_commun', table_name='poisson')
    op.create_index(op.f('ix_poisson_nom_commun'), 'poisson', ['nom_commun'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poisson_nom_commun'), table_name='poisson')
    op.create_index('ix_poisson_nom_commun', 'poisson', ['nom_commun'], unique=True)
    # ### end Alembic commands ###
